version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: php_project-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/init.sql:/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_ROOT_HOST: '%' 
      
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: php_project-php
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./php/content:/usr/src/app